import { GitLabProject } from '../git-lab-api/git-lab-project.model';

export const SAMPLE_PROJECTS: GitLabProject[] = [
  {
    id: 144,
    description:
      'エスエンジニアリング株式会社_空調システム室外ユニットの開発業務支援',
    name: 'gint-chart-test-project',
    name_with_namespace: 'miyoshiyuu / gint-chart-test-project',
    path: 'gint-chart-test-project',
    path_with_namespace: 'miyoshiyuu/gint-chart-test-project',
    created_at: '2024-07-18T08:38:35.708Z',
    default_branch: 'main',
    tag_list: [],
    topics: [],
    ssh_url_to_repo:
      'git@gitlab.example.com:miyoshiyuu/gint-chart-test-project.git',
    http_url_to_repo:
      'https://gitlab.example.com/miyoshiyuu/gint-chart-test-project.git',
    web_url: 'https://gitlab.example.com/miyoshiyuu/gint-chart-test-project',
    readme_url:
      'https://gitlab.example.com/miyoshiyuu/gint-chart-test-project/-/blob/main/README.md',
    forks_count: 0,
    avatar_url: null,
    star_count: 0,
    last_activity_at: '2025-06-16T23:59:56.555Z',
    namespace: {
      id: 4,
      name: 'miyoshiyuu',
      path: 'miyoshiyuu',
      kind: 'user',
      full_path: 'miyoshiyuu',
      parent_id: null,
      avatar_url:
        'https://gitlab.example.com/uploads/-/system/user/avatar/4/avatar.png',
      web_url: 'https://gitlab.example.com/miyoshiyuu',
    },
    _links: {
      self: 'https://gitlab.example.com/api/v4/projects/144',
      issues: 'https://gitlab.example.com/api/v4/projects/144/issues',
      merge_requests:
        'https://gitlab.example.com/api/v4/projects/144/merge_requests',
      repo_branches:
        'https://gitlab.example.com/api/v4/projects/144/repository/branches',
      labels: 'https://gitlab.example.com/api/v4/projects/144/labels',
      events: 'https://gitlab.example.com/api/v4/projects/144/events',
      members: 'https://gitlab.example.com/api/v4/projects/144/members',
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: 'private',
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: '1d',
      enabled: false,
      keep_n: 10,
      older_than: '90d',
      name_regex: '.*',
      name_regex_keep: null,
      next_run_at: '2024-07-19T08:38:35.717Z',
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: 'enabled',
    repository_access_level: 'enabled',
    merge_requests_access_level: 'enabled',
    forging_access_level: 'enabled',
    wiki_access_level: 'enabled',
    builds_access_level: 'enabled',
    snippets_access_level: 'enabled',
    pages_access_level: 'private',
    operations_access_level: 'enabled',
    analytics_access_level: 'enabled',
    container_registry_access_level: 'enabled',
    security_and_compliance_access_level: 'private',
    releases_access_level: 'enabled',
    environments_access_level: 'enabled',
    feature_flags_access_level: 'enabled',
    infrastructure_access_level: 'enabled',
    monitor_access_level: 'enabled',
    model_experiments_access_level: 'enabled',
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 2,
    import_status: 'none',
    open_issues_count: 9,
    ci_config_path: null,
    public_jobs: true,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: 'merge',
    squash_option: 'default_off',
    suggestion_commit_message: null,
    merge_commit_template: null,
    squash_commit_template: null,
    issue_branch_template: null,
    autoclose_referenced_issues: true,
    enforce_auth_checks_on_uploads: true,
    warn_about_potentially_unwanted_characters: true,
    permissions: {
      project_access: {
        access_level: 30,
        notification_level: 3,
      },
      group_access: null,
    },
  },
  {
    id: 145,
    description: 'GINTチャートのフロントエンド開発プロジェクト',
    name: 'gint-chart-frontend',
    name_with_namespace: 'miyoshiyuu / gint-chart-frontend',
    path: 'gint-chart-frontend',
    path_with_namespace: 'miyoshiyuu/gint-chart-frontend',
    created_at: '2023-01-15T10:00:00.000Z',
    default_branch: 'main',
    tag_list: ['Angular', 'TypeScript'],
    topics: ['gantt-chart', 'frontend'],
    ssh_url_to_repo:
      'git@gitlab.example.com:miyoshiyuu/gint-chart-frontend.git',
    http_url_to_repo:
      'https://gitlab.example.com/miyoshiyuu/gint-chart-frontend.git',
    web_url: 'https://gitlab.example.com/miyoshiyuu/gint-chart-frontend',
    readme_url:
      'https://gitlab.example.com/miyoshiyuu/gint-chart-frontend/-/blob/main/README.md',
    forks_count: 2,
    avatar_url: null,
    star_count: 5,
    last_activity_at: '2024-07-19T10:00:00.000Z',
    namespace: {
      id: 4,
      name: 'miyoshiyuu',
      path: 'miyoshiyuu',
      kind: 'user',
      full_path: 'miyoshiyuu',
      parent_id: null,
      avatar_url:
        'https://gitlab.example.com/uploads/-/system/user/avatar/4/avatar.png',
      web_url: 'https://gitlab.example.com/miyoshiyuu',
    },
    _links: {
      self: 'https://gitlab.example.com/api/v4/projects/145',
      issues: 'https://gitlab.example.com/api/v4/projects/145/issues',
      merge_requests:
        'https://gitlab.example.com/api/v4/projects/145/merge_requests',
      repo_branches:
        'https://gitlab.example.com/api/v4/projects/145/repository/branches',
      labels: 'https://gitlab.example.com/api/v4/projects/145/labels',
      events: 'https://gitlab.example.com/api/v4/projects/145/events',
      members: 'https://gitlab.example.com/api/v4/projects/145/members',
    },
    packages_enabled: true,
    empty_repo: false,
    archived: false,
    visibility: 'private',
    resolve_outdated_diff_discussions: false,
    container_expiration_policy: {
      cadence: '1d',
      enabled: false,
      keep_n: 10,
      older_than: '90d',
      name_regex: '.*',
      name_regex_keep: null,
      next_run_at: '2024-07-20T10:00:00.000Z',
    },
    issues_enabled: true,
    merge_requests_enabled: true,
    wiki_enabled: true,
    jobs_enabled: true,
    snippets_enabled: true,
    container_registry_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    can_create_merge_request_in: true,
    issues_access_level: 'enabled',
    repository_access_level: 'enabled',
    merge_requests_access_level: 'enabled',
    forging_access_level: 'enabled',
    wiki_access_level: 'enabled',
    builds_access_level: 'enabled',
    snippets_access_level: 'enabled',
    pages_access_level: 'private',
    operations_access_level: 'enabled',
    analytics_access_level: 'enabled',
    container_registry_access_level: 'enabled',
    security_and_compliance_access_level: 'private',
    releases_access_level: 'enabled',
    environments_access_level: 'enabled',
    feature_flags_access_level: 'enabled',
    infrastructure_access_level: 'enabled',
    monitor_access_level: 'enabled',
    model_experiments_access_level: 'enabled',
    emails_disabled: null,
    shared_runners_enabled: true,
    lfs_enabled: true,
    creator_id: 2,
    import_status: 'none',
    open_issues_count: 25,
    ci_config_path: null,
    public_jobs: true,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: true,
    allow_merge_on_skipped_pipeline: false,
    request_access_enabled: true,
    only_allow_merge_if_all_discussions_are_resolved: true,
    remove_source_branch_after_merge: true,
    printing_merge_request_link_enabled: true,
    merge_method: 'ff',
    squash_option: 'default_off',
    suggestion_commit_message: null,
    merge_commit_template: null,
    squash_commit_template: null,
    issue_branch_template: null,
    autoclose_referenced_issues: true,
    enforce_auth_checks_on_uploads: true,
    warn_about_potentially_unwanted_characters: true,
    permissions: {
      project_access: {
        access_level: 40,
        notification_level: 3,
      },
      group_access: null,
    },
  },
];
