import { Issue } from '@src/app/model/issue.model';

export const SAMPLE_ISSUES: Issue[] = [
  {
    id: 1,
    iid: 1,
    project_id: 144,
    milestone_id: 6,
    title: 'サンプルIssue 1',
    description: 'これはデバッグ用のサンプルIssueです。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['bug', 'urgent'],
    assignee: '田中太郎',
  },
  {
    id: 2,
    iid: 2,
    project_id: 145,
    milestone_id: 43,
    title: 'サンプルIssue 2',
    description: '2件目のサンプルIssueです。',
    start_date: undefined,
    end_date: undefined,
    state: 'closed',
    labels: ['feature'],
    assignee: '佐藤花子',
  },
  // 3件目以降を自動生成
  {
    id: 3,
    iid: 3,
    project_id: 144,
    milestone_id: 6,
    title: 'リファクタリング検討',
    description: 'コードのリファクタリングを検討する。',
    start_date: new Date('2025-06-18'),
    end_date: undefined,
    state: 'opened',
    labels: ['refactor'],
    assignee: '鈴木一郎',
  },
  {
    id: 4,
    iid: 4,
    project_id: 144,
    milestone_id: 6,
    title: 'ドキュメント整備',
    description: 'APIドキュメントを最新化する。',
    start_date: undefined,
    end_date: new Date('2025-06-22'),
    state: 'opened',
    labels: ['docs'],
    assignee: '山田次郎',
  },
  {
    id: 5,
    iid: 5,
    project_id: 144,
    milestone_id: 6,
    title: 'CI/CDパイプライン修正',
    description: 'CI/CDのジョブを見直す。',
    start_date: new Date('2025-06-19'),
    end_date: new Date('2025-06-21'),
    state: 'opened',
    labels: ['ci', 'devops'],
    assignee: '高橋三郎',
  },
  {
    id: 6,
    iid: 6,
    project_id: 144,
    milestone_id: 6,
    title: 'バグ修正：ログイン画面',
    description: 'ログイン画面で発生するバグの修正。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['bug'],
    assignee: '伊藤四郎',
  },
  {
    id: 7,
    iid: 7,
    project_id: 144,
    milestone_id: 7,
    title: '新機能追加：ダークモード',
    description: 'ダークモードのUIを追加する。',
    start_date: new Date('2025-06-15'),
    end_date: new Date('2025-06-25'),
    state: 'opened',
    labels: ['feature', 'ui'],
    assignee: '渡辺五郎',
  },
  {
    id: 8,
    iid: 8,
    project_id: 144,
    milestone_id: 7,
    title: 'パフォーマンス改善',
    description: 'レスポンス速度を改善する。',
    start_date: undefined,
    end_date: new Date('2025-06-23'),
    state: 'opened',
    labels: ['performance'],
    assignee: '小林六郎',
  },
  {
    id: 9,
    iid: 9,
    project_id: 144,
    milestone_id: 7,
    title: 'テストケース追加',
    description: 'ユニットテストを追加。',
    start_date: new Date('2025-06-17'),
    end_date: undefined,
    state: 'opened',
    labels: ['test'],
    assignee: '加藤七郎',
  },
  {
    id: 10,
    iid: 10,
    project_id: 144,
    milestone_id: 44,
    title: 'セキュリティレビュー',
    description: 'コードのセキュリティレビューを実施。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['security'],
    assignee: '吉田八郎',
  },
  // 11〜40件目はバリエーションを持たせて自動生成
  ...Array.from({ length: 30 }, (_, i) => {
    const idx = i + 11;
    return {
      id: idx,
      iid: idx,
      project_id: 145,
      milestone_id: [6, 7, 43, 44, 46, 48][idx % 6],
      title: `サンプルIssue ${idx}`,
      description: `自動生成されたサンプルIssueです（No.${idx}）。`,
      start_date:
        idx % 3 === 0 ? new Date(`2025-06-${10 + (idx % 15)}`) : undefined,
      end_date:
        idx % 4 === 0 ? new Date(`2025-06-${20 + (idx % 10)}`) : undefined,
      state: idx % 2 === 0 ? 'opened' : 'closed',
      labels: [
        idx % 2 === 0 ? 'feature' : 'bug',
        idx % 5 === 0 ? 'urgent' : undefined,
        idx % 7 === 0 ? 'test' : undefined,
      ].filter(Boolean) as string[],
      assignee: `担当者${idx}`,
    };
  }),
];
