import { Issue } from './issue';

export const SAMPLE_ISSUES: Issue[] = [
  {
    id: 1,
    project_id: 144,
    milestone_id: null,
    title: 'サンプルIssue 1',
    description: 'これはデバッグ用のサンプルIssueです。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['bug', 'urgent'],
  },
  {
    id: 2,
    project_id: 145,
    milestone_id: null,
    title: 'サンプルIssue 2',
    description: '2件目のサンプルIssueです。',
    start_date: undefined,
    end_date: undefined,
    state: 'closed',
    labels: ['feature'],
  },
  // 3件目以降を自動生成
  {
    id: 3,
    project_id: 146,
    milestone_id: 1,
    title: 'リファクタリング検討',
    description: 'コードのリファクタリングを検討する。',
    start_date: new Date('2025-06-18'),
    end_date: undefined,
    state: 'opened',
    labels: ['refactor'],
  },
  {
    id: 4,
    project_id: 147,
    milestone_id: 2,
    title: 'ドキュメント整備',
    description: 'APIドキュメントを最新化する。',
    start_date: undefined,
    end_date: new Date('2025-06-22'),
    state: 'opened',
    labels: ['docs'],
  },
  {
    id: 5,
    project_id: 148,
    milestone_id: null,
    title: 'CI/CDパイプライン修正',
    description: 'CI/CDのジョブを見直す。',
    start_date: new Date('2025-06-19'),
    end_date: new Date('2025-06-21'),
    state: 'opened',
    labels: ['ci', 'devops'],
  },
  {
    id: 6,
    project_id: 149,
    milestone_id: null,
    title: 'バグ修正：ログイン画面',
    description: 'ログイン画面で発生するバグの修正。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['bug'],
  },
  {
    id: 7,
    project_id: 150,
    milestone_id: 3,
    title: '新機能追加：ダークモード',
    description: 'ダークモードのUIを追加する。',
    start_date: new Date('2025-06-15'),
    end_date: new Date('2025-06-25'),
    state: 'opened',
    labels: ['feature', 'ui'],
  },
  {
    id: 8,
    project_id: 151,
    milestone_id: null,
    title: 'パフォーマンス改善',
    description: 'レスポンス速度を改善する。',
    start_date: undefined,
    end_date: new Date('2025-06-23'),
    state: 'opened',
    labels: ['performance'],
  },
  {
    id: 9,
    project_id: 152,
    milestone_id: null,
    title: 'テストケース追加',
    description: 'ユニットテストを追加。',
    start_date: new Date('2025-06-17'),
    end_date: undefined,
    state: 'opened',
    labels: ['test'],
  },
  {
    id: 10,
    project_id: 153,
    milestone_id: 4,
    title: 'セキュリティレビュー',
    description: 'コードのセキュリティレビューを実施。',
    start_date: undefined,
    end_date: undefined,
    state: 'opened',
    labels: ['security'],
  },
  // 11〜40件目はバリエーションを持たせて自動生成
  ...Array.from({ length: 30 }, (_, i) => {
    const idx = i + 11;
    return {
      id: idx,
      project_id: 200 + (idx % 10),
      milestone_id: idx % 5 === 0 ? idx % 3 : null,
      title: `サンプルIssue ${idx}`,
      description: `自動生成されたサンプルIssueです（No.${idx}）。`,
      start_date:
        idx % 3 === 0 ? new Date(`2025-06-${10 + (idx % 15)}`) : undefined,
      end_date:
        idx % 4 === 0 ? new Date(`2025-06-${20 + (idx % 10)}`) : undefined,
      state: idx % 2 === 0 ? 'opened' : 'closed',
      labels: [
        idx % 2 === 0 ? 'feature' : 'bug',
        idx % 5 === 0 ? 'urgent' : undefined,
        idx % 7 === 0 ? 'test' : undefined,
      ].filter(Boolean) as string[],
    };
  }),
];
